{% set version = "8.0.13" %}

package:
  name: thinc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/thinc/thinc-{{ version }}.tar.gz
  sha256: 47662a3ae33d445a77b6ea7b772444805c7bba8991f122e350daf72dedc8171a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # 2021/11/08: thinc 8.0.13 requires cython-blis >=0.4.0,<0.8.0
  # but it's not available on win32 on defaults 
  skip: True  # [win32]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.25,<3.0
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=0.28.0,<1.1.0
    - cython-blis >=0.4.0,<0.8.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<1.9.0  # [arm64]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=0.4.0,<0.8.0
    - wasabi >=0.8.1,<1.1.0
    - srsly >=2.4.0,<3.0.0
    - catalogue >=2.0.4,<2.1.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<1.9.0
    - typing_extensions >=3.7.4.1,<4.0.0.0  # [py<=37]

test:
  requires:
    - hypothesis
    - pytest
    - mock
    - pathy >=0.3.5
  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

  commands:
    - python -m pytest --tb=native --pyargs thinc

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.
  dev_url: https://github.com/explosion/thinc/

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd