{% set name = "thinc" %}
{% set version = "6.12.0" %}
{% set sha256sum = "757ae2d54250e30919aa3171a64c801f28ac74446e8b9fc44a32e7b31170cd51" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [blas_impl == 'openblas' and win]
  missing_dso_whitelist:
    - libcudart.so.9.1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and vc<14]
    - python
    - setuptools
    - numpy
    - mkl-devel {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    # setup.py has wheel in setup_requires
    - wheel >=0.32.0,<0.33.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - msgpack-python >=0.5.6,<1.0.0
    - msgpack-numpy <0.4.4.0
    - murmurhash >=0.28,<1.1.0
    - cymem >=2.0.2,<3.0.0
    - preshed >=2.0.1,<3.0.0
    - cytoolz >=0.9.0,<0.10
    - wrapt >=1.10.10,<1.11.0
    - plac >=0.9.6,<1.0
    - tqdm >=4.10.0,<5.0.0
    - six >=1.10.0,<2.0.0
    - dill >=0.2.7,<0.3.0
    - pathlib >=1.0.0,<2.0.0  # [py27]

test:
  requires:
    - hypothesis
    - pytest
    - mock
    - nomkl  # [x86 and blas_impl != 'mkl']

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.extra._vendorized
    - thinc.neural
    - thinc.neural._classes

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.
  dev_url: https://github.com/explosion/thinc

extra:
  recipe-maintainers:
    - rmax
