{% set name = "thinc" %}
{% set version = "9.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21fae2986d7777a6f050b9046dc9eab11852f1c9a997dcc9032f3ecc22784a4a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # Cython 0.29.37 is not available for Py 313.
  skip: True  # [py<39 or py>312]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - wheel
    - setuptools
    - cython >=0.25,<3.0
    - murmurhash >=1.0.2,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=1.0.0,<1.1.0
    - numpy >=2.0.0,<3.0.0  # [py<39]
  run:
    - python
    - numpy >=1.19.0,<3.0.0
    - cython-blis >=1.0.0,<1.1.0
    - murmurhash >=1.0.2,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - wasabi >=0.8.1,<1.2.0
    - srsly >=2.4.0,<3.0.0
    - catalogue >=2.0.4,<2.1.0
    - confection >=0.0.1,<1.0.0
    - setuptools
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0
    - packaging >=20.0
  run_constrained:
    # datasets
    - ml_datasets >=0.2.0,<0.3.0
    # mxnet
    - mxnet >=1.5.1,<1.6.0
    # tensorflow
    - tensorflow >=2.0.0,<2.6.0
    # torch
    - pytorch >=1.6.0

test:
  imports:
    - thinc
    - thinc.api
    - thinc.backends
    - thinc.backends._custom_kernels
    - thinc.backends._param_server
    - thinc.compat
    - thinc.config
    - thinc.layers
    - thinc.layers.gelu
    - thinc.layers.parametricattention_v2
    - thinc.layers.pytorchwrapper
    - thinc.layers.resizable
    - thinc.layers.uniqued
    - thinc.model
    - thinc.optimizers
    - thinc.schedules
    - thinc.shims.pytorch
    - thinc.shims.pytorch_grad_scaler
    - thinc.shims.shim
    - thinc.types
    - thinc.util
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs thinc
  requires:
    - hypothesis
    - pytest
    - mock
    - pip

about:
  home: https://thinc.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A refreshing functional take on deep learning, compatible with your favorite libraries.
  description: |
    Thinc is a lightweight deep learning library that offers an elegant, type-checked, functional-programming API 
    for composing models, with support for layers defined in other frameworks 
    such as PyTorch, TensorFlow and MXNet. You can use Thinc as an interface layer, a standalone toolkit 
    or a flexible way to develop new models. Previous versions of Thinc have been running quietly in production in thousands of companies, 
    via both spaCy and Prodigy.
  dev_url: https://github.com/explosion/thinc
  doc_url: https://thinc.ai/docs

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
  skip-lints:
    - cython_needs_compiler
    - python_build_tool_in_run
    - should_use_stdlib