{% set version = "8.0.15" %}

package:
  name: thinc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/thinc/thinc-{{ version }}.tar.gz
  sha256: 2e315020da85c3791e191fbf37c4a2433f57cf322e27380da0cd4de99d96053b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<36]
  # 2021/11/08: thinc 8.0.13 requires cython-blis >=0.4.0,<0.8.0
  # but it's not available on win32 on defaults 
  skip: True  # [win32]
  # 2021/11/11: skip s390x as many dependencies are not on this platform: 
  # e.x., preshed, cython-blis, cymem, murmurhash. 
  skip: True  # [s390x]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.25,<3.0
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=1.0.2,<1.1.0
    - cython-blis >=0.4.0,<0.8.0 
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<1.9.0 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=1.0.2,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=0.4.0,<0.8.0
    - wasabi >=0.8.1,<1.1.0
    - srsly >=2.4.0,<3.0.0
    - catalogue >=2.0.4,<2.1.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<1.9.0
    - setuptools
    # Backports of modern Python features
    - typing_extensions >=3.7.4.1,<4.0.0.0  # [py<38]

test:
  imports:
    - thinc
    - thinc.api
    - thinc.extra
  commands:
    # FileNotFoundError: [Errno 2] No such file or directory: 'gs://test-bucket/thinc_model',
    # 'gs://test-bucket/cool_shim.data', and 'gs://test-bucket/config.cfg'
    #- python -m pytest --tb=native --pyargs thinc -k "not (test_config_roundtrip_disk_respects_path_subclasses or test_shim_can_roundtrip_with_path_subclass or test_model_can_roundtrip_with_path_subclass)"

about:
  home: https://thinc.ai/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.
  dev_url: https://github.com/explosion/thinc/
  doc_url: https://thinc.ai/docs

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd