{% set name = "thinc" %}
{% set version = "8.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e8ef69eac89a601e11d47fc9e43d26ffe7ef682dcf667c94ff35ff690549aeb
  patches:
    - loosen-numpy-bounds.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # numpy-base >=2.0.0 requires python >=3.9
  skip: True  # [py<39]
  # 2021/11/11: skip s390x as many dependencies are not on this platform:
  # e.x., preshed, cython-blis, cymem, murmurhash.
  skip: True  # [s390x]

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch # [unix]
    - m2-patch # [win]
  host:
    - cymem >=2.0.2,<2.1.0
    - cython >=0.25,<3.0
    - cython-blis >=1.0.0,<1.1.0
    - murmurhash >=1.0.2,<1.1.0
    - numpy >=2.0.0,<3.0.0
    - pip
    - preshed >=3.0.2,<3.1.0
    - python
    - setuptools
    - wheel
  run:
    - python
    # loosened bounds as per https://github.com/explosion/thinc/compare/release-v8.3.2...release-v8.3.4
    - numpy>=1.19.0,<3.0.0
    - murmurhash >=1.0.2,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=1.0.0,<1.1.0
    - wasabi >=0.8.1,<1.2.0
    - srsly >=2.4.0,<3.0.0
    - catalogue >=2.0.4,<2.1.0
    - confection >=0.0.1,<1.0.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0
    - packaging >=20.0
    - setuptools

test:
  requires:
    - hypothesis >=3.27.0,<6.72.2
    - pytest >=5.2.0,!=7.1.0
    - mock
    - pip
  imports:
    - thinc
    - thinc.api
    - thinc.backends
    - thinc.extra
    - thinc.layers
    - thinc.shims
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs thinc

about:
  home: https://thinc.ai/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A refreshing functional take on deep learning, compatible with your favorite libraries.
  description: |
    Thinc is a lightweight deep learning library that offers an elegant, type-checked, functional-programming API 
    for composing models, with support for layers defined in other frameworks 
    such as PyTorch, TensorFlow and MXNet. You can use Thinc as an interface layer, a standalone toolkit 
    or a flexible way to develop new models. Previous versions of Thinc have been running quietly in production in thousands of companies, 
    via both spaCy and Prodigy.
  dev_url: https://github.com/explosion/thinc/
  doc_url: https://thinc.ai/docs

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
  skip-lints:
    - cython_needs_compiler
    - python_build_tool_in_run
