travis:
  secure:
    BINSTAR_TOKEN: zq7+DYMGWvq4uIyNzomFTv0e5HC+cSTDJFs5mi+4x9wQ07HUYWJALN1KigFediVaa92ocF66QydCiVJldkowEd0z39DrFER1AOYMHPEgJ70r7LyWrsQBF6ST173wPwYvKtBto9UtZ43xqypuCG26VUMueszbxtX2Qn2XgqBRgroNhSEGlbYo927sZngt3Qt01jpySxX99yJi+nFFUNbXlW/+FKps3sOqc/Qb2RkvZRWlaxIgjDZDUUqfLSzvnWrn4DyVvMCPuIUeXHMJ8QIjBoNyKATkIVO2q9EpAeaTirTB4bMhNg9lHW2CVgfGaJR8/+AQ2iGV9gQ3vNR4x7xJZ4P4zxW3rCu0esXiZ/HF9zJV4rAymtrd5jtyTPmPNuMlrWTt5hiwww95zBov60TM1EncSabjbYqm9LZAFH+AhZnZ2QiRyMVl57M+YoFvwVLqlAsOFrcg4/aXrwzYhGnc6IG4sEQ47gKXZjlWQg8hbGuwh1tYJfOXy3v+4f7ZW3yFWon5vJSVOiBNf+AeblikfprYjbqbKGpGPVlcGpcucXSFt4wmQgfHcKVSfLv0lt/vqu6oAfxHNohEVjLuh4wuRLRqP77XYNoSjz3BBZk/NflRAr50Vp13IFx1K+s7u8HkkPUBYrEoBShZctGoYId2axviuc+9gmDk5LEwl/3Mcd4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
