travis:
  secure:
    BINSTAR_TOKEN: QJiSVbZHChrtKmVpFTEWOULt8OTMzAV3GKef/0b3UkzEYf+iSI631u4NA50FqhZSiGzAhJB5c9urwFBzQ6T20RMOrmLOOPL7mzPKG/dPbqdr5TQ/r3HGXd5CgP+LzWVf32LflWGzDX/OiLsOsrZI98Uec84Iyba2amPHpMZ9bTuScSd+YViiMSZ7jdDlMVn7DCx2FgrJhK0mKPUHundW8NKU9CssnZuQ87iNshVTSWCRCXVd5nhABaWGQZSKEiem95cxAahgay+QpkKlUj9pbz+jJPzl8B1NgOiMxFvLLhfT8qT4ezBdc2tw8VXCHmakXCAw6amcNL6jdEN9cpSBdfS/5wXZiOUo4bQHVANfFwmKJU1ufS4bvZsSsjv9PscCH8Izoe89RvTzEN3RYUThgU1x1JU4ApoRjxgR9Jy8BC09gyXKUucdYgNsZRKeFK9XdW2Qh+kcPsgIMc3Tc3SbETp9qWJoWispiNGoWEQGOgrjRwf3ihjTDpey5CDz3CQL8ULSttcdjpnglN27L6/OjE/tJkQprkKCUZXQJz8a1xuCt9tClVW618w6dUThFTklodu453D84dqwg7j2zsLmaUx/pN0XXO/uX2R1fi1//suQhrX2ZJs3bRbVHsMt1Li9o2YGKYb8e58kcLaXX2q/JdQsMpgfuHPG8fHwXgRLA8A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
