travis:
  secure:
    BINSTAR_TOKEN: K4ZLYUI0RQ3PapFmxktmSBB4ImSfxhZjRrWDiDE0o1M6AgCa++eD78V1hqh/EO3MRZSb8xQ/cqZCBa5CjH5B4tfQ83bo3FyDk3ucZ9Sve60M4c8MIcC5z5lD2QLrxoUoavOl96FHC2/1j9mVXNjDz2bEFSeqgi6DkNjW4LhrxzMAekHY+WdZKx1zEdRehdQjyXMmP6V64Tpdhi2tUeTZre3JUS+3nlBX9GXRWtXF6WHJxhBFsgbP8B7dSbmIyXkNYVxaKqEXSywU0Ec+Mbe2rR7Hg8hLYx/U3sotyQgOcA5UxBJBXWsLAHrQAORfkMXcCv5kDL8XwKCvlxOR/iorY+2nc9tjYrcnLIyxdx0K4/BDltiX9NB319ACHZil1o7HbftOa7BozA8LJ540hdzsCl7nMRai1xidnkq5de82ic2sS902f5VaCOdNmmOzzB7xXBOw+/k5Dt/Wm/kCv9MkRqD54M3i3TX1jrZhQlWgua9sdMQkHv4YOpK90sdPMrXQSSUjGgrEfNnbXX0P1Bvi8gohDlOoqRKVwFgu4O6Yr/Qesa7oYhRo2XwZfo+5JyExHwPlNMMyoQVpkPtTFfi7uZoll+7hTNIRhpUMKB4DSQLd2xMGFFS3BoevcN1lt0n45Rb1DxHRgDUbsSX2wtvBwQh6tj5Mo0BKndQhy8788GI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
